### ISSUE TITLE
Invalid symbols in the name generation

### ISSUE THREAD

**Issue by Darkratos** [cursey/ue4genny#5]
Hello, I'm working on a mod for Ender Lilies and came across an issue while dumping.
Basically there are some classes being generated with a '+' in the middle.
I made a band-aid fix here but thought you should know.
Other than that, great project!

**Comment by cursey** [comment]
Try upgrading the version of SdkGenny being used (https://github.com/cursey/sdkgenny). Newer versions of SdkGenny have improvements so that the names being generated should be valid. I just haven't gotten around to merging in the latest changes since I'm not actively modding a UE4 game at the moment.

Happy to hear the project is useful.

**Comment by Darkratos** [comment]
I still had to patch the 'usable_name' function to include the plus sign, and it seems to have worked now.
Anyways, thanks for the quick answer!

**Comment by cursey** [comment]
Could you paste a diff of the change you applied to fix the issue?

**Comment by Darkratos** [comment]
Sorry, I didn't notice the reply.
I basically only added a check "|| c =='+' ". Your solution was way better than mine.
